title: westpa-deepdrivemd
resource: tacc.longhorn
queue: v100
schema_: local
project: MCB20024
walltime_min: 230
max_iteration: 2
cpus_per_node: 10
gpus_per_node: 4
hardware_threads_per_cpu: 4
experiment_directory: /scratch/06079/tg853783/ddmd/runs/westpa_deepdrivemd_5th
node_local_path: null
molecular_dynamics_stage:
    pre_exec: 
    - module load cuda
    - alias ibrun="/scratch/06079/tg853783/ddmd/src/ibrun_new"
    - module unload spectrum_mpi
    executable: '/scratch/06079/tg853783/ddmd/envs/ddmd/bin/python'
    arguments: ['/scratch/06079/tg853783/ddmd/src/DeepDriveMD-pipeline/deepdrivemd/sim/openmm/run_openmm.py']
    cpu_reqs:
        processes: 1
        process_type: null
        threads_per_process: 1
        thread_type: null
    gpu_reqs:
        processes: 1
        process_type: null
        threads_per_process: 1
        thread_type: null
    num_tasks: 12
    task_config:
        experiment_directory: set_by_deepdrivemd
        stage_idx: 0
        task_idx: 0
        output_path: set_by_deepdrivemd
        node_local_path: set_by_deepdrivemd
        pdb_file: /scratch/06079/tg853783/ddmd/data/system/westpa_deepdrivemd/closed.pdb
        initial_pdb_dir: /scratch/06079/tg853783/ddmd/data/system/
        reference_pdb_file: /scratch/06079/tg853783/ddmd/data/system/westpa_deepdrivemd/closed.pdb
        solvent_type: explicit
        top_suffix: .prmtop
        simulation_length_ns: 0.1
        report_interval_ps: 1.0
        dt_ps: 0.002
        temperature_kelvin: 310.0
        heat_bath_friction_coef: 1.0
        wrap: false
        openmm_selection:
                - CA
        mda_selection: protein and name CA
        threshold: 8.0
        contact_map: true
        point_cloud: true
        fraction_of_contacts: true
        is_memory: false
aggregation_stage:
    pre_exec: []
    executable: ''
    arguments: []
    cpu_reqs:
        processes: 1
        process_type: null
        threads_per_process: 1
        thread_type: null
    gpu_reqs:
        processes: 0
        process_type: null
        threads_per_process: 0
        thread_type: null
    skip_aggregation: true
    task_config:
        experiment_directory: set_by_deepdrivemd
        stage_idx: 0
        task_idx: 0
        output_path: set_by_deepdrivemd
        node_local_path: set_by_deepdrivemd
machine_learning_stage:
    pre_exec: 
    - 'module purge'
    - 'module load xl git cmake TACC spectrum_mpi autotools xalt conda'
    - 'export IBRUN_TASKS_PER_NODE=4'
    - 'export HDF5_USE_FILE_LOCKING=FALSE'
    - alias ibrun="/scratch/06079/tg853783/ddmd/src/ibrun_new"
    executable: cat /dev/null; ibrun -n 4 /scratch/06079/tg853783/ddmd/src/DeepDriveMD-Longhorn-2021/ddp_aae_experiments/aae_run.sh
    arguments: 
    - /scratch/06079/tg853783/ddmd/envs/pytorch.mpi/bin/python
    - /scratch/06079/tg853783/ddmd/src/DeepDriveMD-pipeline/deepdrivemd/models/aae/train.py
    cpu_reqs:
        processes: 4
        process_type: 'MPI'
        threads_per_process: 1
        thread_type: 'OpenMP'
    gpu_reqs:
        processes: 1
        process_type: null
        threads_per_process: 1
        thread_type: null
    retrain_freq: 1
    task_config:
        experiment_directory: set_by_deepdrivemd
        stage_idx: 0
        task_idx: 0
        output_path: set_by_deepdrivemd
        node_local_path: set_by_deepdrivemd
        model_tag: set_by_deepdrivemd
        init_weights_path: /scratch/06079/tg853783/ddmd/runs/ddp_aae_experiments/1-node_128-gbs/checkpoint/epoch-100-20210727-180344.pt
        last_n_h5_files: 12
        k_random_old_h5_files: 12
        dataset_name: point_cloud
        rmsd_name: rmsd
        fnc_name: rmsd
        num_points: 3375
        num_features: 0
        initial_epochs: 10
        epochs: 10
        batch_size: 32
        optimizer_name: Adam
        optimizer_lr: 0.0001
        latent_dim: 64
        encoder_filters:
        - 64
        - 128
        - 256
        - 256
        - 512
        encoder_kernel_sizes:
        - 5
        - 5
        - 3
        - 1
        - 1
        generator_filters:
        - 64
        - 128
        - 512
        - 1024
        discriminator_filters:
        - 512
        - 512
        - 128
        - 64
        encoder_relu_slope: 0.0
        generator_relu_slope: 0.0
        discriminator_relu_slope: 0.0
        use_encoder_bias: true
        use_generator_bias: true
        use_discriminator_bias: true
        noise_mu: 0.0
        noise_std: 1.0
        lambda_rec: 0.5
        lambda_gp: 10.0
        embed_interval: 10
        checkpoint_interval: 10
        sample_interval: 5
        tsne_interval: 101
        num_data_workers: 0
        dataset_location: storage
model_selection_stage:
    pre_exec: 
    - 'export IBRUN_TASKS_PER_NODE=40'
    - alias ibrun="/scratch/06079/tg853783/ddmd/src/ibrun_new"
    executable: '/scratch/06079/tg853783/ddmd/envs/pytorch.mpi/bin/python'
    arguments: ['/scratch/06079/tg853783/ddmd/src/DeepDriveMD-pipeline/deepdrivemd/selection/latest/select_model.py']
    cpu_reqs:
        processes: 1
        process_type: null
        threads_per_process: 1
        thread_type: null
    gpu_reqs:
        processes: 0
        process_type: null
        threads_per_process: 0
        thread_type: null
    task_config:
        experiment_directory: set_by_deepdrivemd
        stage_idx: 0
        task_idx: 0
        output_path: set_by_deepdrivemd
        node_local_path: set_by_deepdrivemd
        retrain_freq: 1
        checkpoint_dir: checkpoint
        checkpoint_suffix: .pt
agent_stage:
    pre_exec:
    - alias ibrun="/scratch/06079/tg853783/ddmd/src/ibrun_new"
    executable: '/scratch/06079/tg853783/ddmd/envs/pytorch.mpi/bin/python'
    arguments: ['/scratch/06079/tg853783/ddmd/src/DeepDriveMD-pipeline/deepdrivemd/agents/lof/lof.py']
    cpu_reqs:
        processes: 1
        process_type: null
        threads_per_process: 1
        thread_type: null
    gpu_reqs:
        processes: 0
        process_type: null
        threads_per_process: 0
        thread_type: null
    task_config:
        experiment_directory: set_by_deepdrivemd
        stage_idx: 0
        task_idx: 0
        output_path: set_by_deepdrivemd
        node_local_path: set_by_deepdrivemd
        num_intrinsic_outliers: 12
        num_extrinsic_outliers: 12
        intrinsic_score: lof
        extrinsic_score: null
        n_traj_frames: 100
        n_most_recent_h5_files: 12
        k_random_old_h5_files: 12
        sklearn_num_jobs: -1
        model_type: "AAE3d"
        inference_batch_size: 128

